### ISSUE TITLE
I try to add join message to EventHandler class.

### ISSUE THREAD

**Issue by MassiveLag** [Snazzah/Faux#1]
Hi, i try to add a serverpoller to my discord bot, like it shows the playercount of a minecraft server on a channel and it updates every x minutes. Do you know a way to do this?

And i try to filter member count on Eventhandler class for a join message, but it says 

Cannot read property 'guild' of undefined

The code looks like this

```js
  async onMemberJoin(client, member, message){
    this.client.stats.bumpStat('users')
    const guildID = member.guild.id;
    let guild = this.client.guilds.get(guildId);
    console.log(member.guild, member.guildID, guild.members.size);
    const humans = [guild.members.size - guild.members.filter(member => member.user.bot).size]
    //const humans = guild.members.filter(member => !member.user.bot).size;
    this.client.user.setPresence({ game: { name: humans }, status: 'online' });
  }
}
```

Thanks for reading

**Comment by Snazzah** [comment]
please read d.js docs
